version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  install-node:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          - install-yarn: true
          - install-npm: false
          - node-version: 14.12.0
          - yarn-version: 1.22.10
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: git config user.email "jwong123@binghamton.edu"
      - run: git config user.name "Jonathan Wong"
      - run: yarn install
      - run: yarn build
      - run: yarn push
workflows:
  install-node:
    jobs:
      - install-node
  build-and-test:
    jobs:
      - build-and-test:
        filters:
          branches:
            only: develop
