version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  branches:
    ignore:
      - master
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: git config user.email "jwong123@binghamton.edu"
            - run: git config user.name "Jonathan Wong"
            - run: yarn install
            - run: yarn build
            - run: yarn push
workflows:
    build-and-test:
      jobs:
        - build-and-test