version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  pusher:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: 14.12.0
          yarn-version: 1.22.10
      - run: git config user.email "jwong123@binghamton.edu"
      - run: git config user.name "Jonathan Wong"
      - run: yarn install
      - run: yarn build
      - run: yarn push
workflows:
  build-and-test:
    jobs:
      - pusher:
        filters:
          branches:
            only: 
              - develop
