version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      install:
        parameters:
          install-npm:
            default: false
            description: Install NPM?
            type: boolean
          install-yarn:
            default: true
            description: Install Yarn?
            type: boolean
          steps:
            - run:
              command: |
              git config user.email "jwong123@binghamton.edu"
              git config user.name "Jonathan Wong"
              yarn install
              yarn build
              yarn push
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        filters:
          branches:
            only: develop
